name: chatting
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.16.1 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  firebase_auth: ^3.3.11
  firebase_core: ^1.13.1
  flutter:
    sdk: flutter
  google_sign_in: ^5.2.4
  provider: ^6.0.2

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
